services:
  # This project adds a two-way-sync between trakt.tv and Plex Media Server.
  # It requires a trakt.tv account but no Plex premium and no Trakt VIP subscriptions,
  # unlike the Plex app provided by Trakt.
  # DOCS -- https://github.com/Taxel/PlexTraktSync
  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    volumes:
      - ${DOCKER_DIR}/plextraktsync:/app/config
    labels:
      - ofelia.enabled=true
      # ------------------------------------------------------------------------
      # PULLIO
      # ------------------------------------------------------------------------
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.update=true
      - org.hotio.pullio.generic.webhook=https://notifiarr.com/api/v1/notification/pullio/${PULLIO_API_KEY}

networks:
  default:
    name: media-apps_apps
    external: true
