# ----------------------------------------------------------------------------------------------
# CONFIGURATION DOCS: https://www.authelia.com/configuration/prologue/introduction/
# ----------------------------------------------------------------------------------------------

log:
  level: warn
  file_path: /config/authelia.log

server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  # path: 'authelia'
  # jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE

default_redirection_url: https://auth.YOURDOMAIN.COM/

password_policy:
  standard:
    enabled: true
    min_length: 16
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

# ----------------------------------------------------------------------------------------------
# AUTHENTICATION FIST FACTOR
# ----------------------------------------------------------------------------------------------

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  # ldap:
  #   #implementation: custom
  #   # The url to the ldap server. Scheme can be ldap:// or ldaps://
  #   url: ldaps://<LDAP-SERVER-IP>
  #   skip_verify: true
  #   base_dn: dc=<INT>,dc=<YOUR-DOMAIN>,dc=<COM>
  #   username_attribute: uid
  #   additional_users_dn: cn=users
  #   # Recommended settings are as follows:
  #   # - Microsoft Active Directory: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
  #   # - OpenLDAP: (&({username_attribute}={input})(objectClass=person))' or '(&({username_attribute}={input})(objectClass=inetOrgPerson))
  #   #
  #   # To allow sign in both with username and email, one can use a filter like
  #   # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
  #   users_filter: (&({username_attribute}={input})(objectClass=person))
  #   additional_groups_dn: cn=groups
  #   groups_filter: (&(member={dn})(objectclass=groupOfNames))
  #   group_name_attribute: cn
  #   mail_attribute: mail
  #   user: uid=root,cn=users,dc=<INT>,dc=<YOUR-DOMAIN>,dc=<COM>
  #   # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
  #   # password: password
  file:
    path: /config/users.yml
    password:
      algorithm: argon2id
      iterations: 3
      key_length: 32
      salt_length: 16
      parallelism: 4
      memory: 64

# ----------------------------------------------------------------------------------------------
# 2FA
# ----------------------------------------------------------------------------------------------

totp:
  disable: true
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

duo_api:
  disable: false
  hostname: APIENDPOINTHOSTNAME
  integration_key: YOURINTEGRATIONKEY
  # secret_key: # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE

webauthn:
  disable: true
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s

access_control:
  default_policy: deny
  rules:
    # ----------------------------------------------------------------------------------------------
    # Policies below bypass oauth as for api calls
    # ----------------------------------------------------------------------------------------------
    # BAZARR
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'bazarr.YOURDOMAIN.COM'
        - 'bazarr-4k.YOURDOMAIN.COM'
      resources:
        - '^(/bazarr(-4k)?)?/api/.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # PROWLARR
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'prowlarr.YOURDOMAIN.COM'
      resources:
        - '^(/prowlarr)?/api/.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # LIDARR
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'lidarr.YOURDOMAIN.COM'
      resources:
        - '^(/lidarr)?/api/.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # READARR
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'readarr.YOURDOMAIN.COM'
      resources:
        - '^(/readarr)?/api/.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # RADARR
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'radarr.YOURDOMAIN.COM'
        - 'radarr-4k.YOURDOMAIN.COM'
      resources:
        - '^(/radarr(-4k)?)?/api/.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # SONARR
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'sonarr.YOURDOMAIN.COM'
        - 'sonarr-4k.YOURDOMAIN.COM'
      resources:
        - '^(/sonarr(-4k)?)?/api/.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # SABNZBD
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'sabnzbd.YOURDOMAIN.COM'
      resources:
        - '^(/sabnzbd)?/api.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # NZBGET
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'nzbget.YOURDOMAIN.COM'
      resources:
        - '^(/nzbget)?(/[^\/:]*:[^\/]*)?/(jsonrpc|jsonprpc|xmlrpc).*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # PORTAINER
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'portainer.YOURDOMAIN.COM'
      resources:
        - '^(/portainer)?/api/websocket.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # QBITTORRENT
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'qb.YOURDOMAIN.COM'
      resources:
        - '^(/qb)?/api.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # TAUTULLI
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'tautulli.YOURDOMAIN.COM'
        - 'tautulli-4k.YOURDOMAIN.COM'
      resources:
        - '^(/tautulli(-4k)?)?/api.*$'
      policy: bypass
    # ----------------------------------------------------------------------------------------------
    # end bypass policies
    # ----------------------------------------------------------------------------------------------
    # ----------------------------------------------------------------------------------------------
    # MAIN DOMAIN SECTION
    # ----------------------------------------------------------------------------------------------
    - domain:
        - 'YOURDOMAIN.COM'
        - 'auth.YOURDOMAIN.COM'
      resources:
        - '^(/auth).*$'
      policy: bypass
    - domain: '*.YOURDOMAIN.COM'
      policy: two_factor
    - domain: 'YOURDOMAIN.COM'
      policy: two_factor

session:
  name: authelia_session
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1w
  domain: YOURDOMAIN.COM

  redis:
    host: authredis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: ${REDIS_PASSWORD}

storage:
  encryption_key: STORAGEENCRYPTIONKEY
  mysql:
    host: authmariadb
    port: 3306
    database: authelia
    username: authelia

notifier:
  smtp:
    username: SMTPSERVERUSERNAME
    # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: smtp.gmail.com
    port: 587
    sender: SMTPSERVERUSERNAME
  # filesystem:
  #   filename: /tmp/authelia/notification.txt
